CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='eoms_app') THEN CREATE ROLE eoms_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS; END IF; END $$;
CREATE SCHEMA IF NOT EXISTS eoms;
REVOKE ALL ON SCHEMA eoms FROM PUBLIC;
GRANT USAGE ON SCHEMA eoms TO eoms_app;
CREATE TABLE eoms.users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE,display_name text NOT NULL,password_hash text NOT NULL,active boolean NOT NULL DEFAULT true);
CREATE TABLE eoms.sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES eoms.users(id),csrf text NOT NULL,expires_at timestamptz NOT NULL);
CREATE INDEX sessions_expiry ON eoms.sessions(expires_at);
CREATE TABLE eoms.companies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL);
CREATE TABLE eoms.estates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES eoms.companies(id),code text UNIQUE NOT NULL,name text NOT NULL);
CREATE TABLE eoms.memberships(user_id uuid NOT NULL REFERENCES eoms.users(id),estate_id uuid NOT NULL REFERENCES eoms.estates(id),role text NOT NULL CHECK(role IN ('manager','supervisor','clerk')),PRIMARY KEY(user_id,estate_id));
CREATE INDEX membership_estate_user ON eoms.memberships(estate_id,user_id);
CREATE TABLE eoms.workers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),estate_id uuid NOT NULL REFERENCES eoms.estates(id),code text NOT NULL,name text NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(estate_id,id),UNIQUE(estate_id,code));
CREATE TABLE eoms.occurrences(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),estate_id uuid NOT NULL REFERENCES eoms.estates(id),block_code text NOT NULL,task_code text NOT NULL,activity text NOT NULL,round_code text NOT NULL,capacity_ha numeric(12,2) NOT NULL CHECK(capacity_ha>0),UNIQUE(estate_id,id),UNIQUE(estate_id,block_code,task_code,activity,round_code));
CREATE TABLE eoms.periods(estate_id uuid NOT NULL REFERENCES eoms.estates(id),month date NOT NULL CHECK(extract(day FROM month)=1),locked boolean NOT NULL DEFAULT false,PRIMARY KEY(estate_id,month));
CREATE TABLE eoms.musters(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),estate_id uuid NOT NULL REFERENCES eoms.estates(id),occurrence_id uuid NOT NULL,business_date date NOT NULL,gang_code text NOT NULL,quantity_ha numeric(12,2) NOT NULL CHECK(quantity_ha>0),status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','confirmed')),version integer NOT NULL DEFAULT 1,created_by uuid NOT NULL REFERENCES eoms.users(id),created_at timestamptz NOT NULL DEFAULT now(),confirmed_at timestamptz,FOREIGN KEY(estate_id,occurrence_id) REFERENCES eoms.occurrences(estate_id,id),UNIQUE(estate_id,id));
CREATE INDEX muster_estate_date_id ON eoms.musters(estate_id,business_date DESC,id DESC);
CREATE INDEX muster_occurrence_confirmed ON eoms.musters(estate_id,occurrence_id,status);
CREATE TABLE eoms.muster_shares(estate_id uuid NOT NULL,muster_id uuid NOT NULL,worker_id uuid NOT NULL,quantity_ha numeric(12,2) NOT NULL CHECK(quantity_ha>=0),man_days numeric(3,2) NOT NULL CHECK(man_days IN(.25,.5,.75,1)),PRIMARY KEY(muster_id,worker_id),FOREIGN KEY(estate_id,muster_id) REFERENCES eoms.musters(estate_id,id),FOREIGN KEY(estate_id,worker_id) REFERENCES eoms.workers(estate_id,id));
CREATE TABLE eoms.audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,estate_id uuid NOT NULL REFERENCES eoms.estates(id),actor_id uuid NOT NULL REFERENCES eoms.users(id),action text NOT NULL,record_id uuid,detail jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_estate_id ON eoms.audit(estate_id,id DESC);
CREATE TABLE eoms.outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),estate_id uuid NOT NULL REFERENCES eoms.estates(id),aggregate_id uuid NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(estate_id,aggregate_id,event_type));
CREATE TABLE eoms.idempotency(estate_id uuid NOT NULL REFERENCES eoms.estates(id),user_id uuid NOT NULL REFERENCES eoms.users(id),key text NOT NULL,request_hash text NOT NULL,response jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(estate_id,user_id,key));
CREATE FUNCTION eoms.actor_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.user_id',true),'')::uuid $$;
CREATE FUNCTION eoms.is_member(estate uuid) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT EXISTS(SELECT 1 FROM eoms.memberships WHERE estate_id=estate AND user_id=eoms.actor_id()) $$;
ALTER TABLE eoms.memberships ENABLE ROW LEVEL SECURITY; ALTER TABLE eoms.memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY membership_self ON eoms.memberships FOR SELECT TO eoms_app USING(user_id=eoms.actor_id());
ALTER TABLE eoms.estates ENABLE ROW LEVEL SECURITY; ALTER TABLE eoms.estates FORCE ROW LEVEL SECURITY;
CREATE POLICY estate_member ON eoms.estates FOR SELECT TO eoms_app USING(eoms.is_member(id));
ALTER TABLE eoms.companies ENABLE ROW LEVEL SECURITY; ALTER TABLE eoms.companies FORCE ROW LEVEL SECURITY;
CREATE POLICY company_member ON eoms.companies FOR SELECT TO eoms_app USING(EXISTS(SELECT 1 FROM eoms.estates e WHERE e.company_id=companies.id));
DO $$ DECLARE tab text; BEGIN FOREACH tab IN ARRAY ARRAY['workers','occurrences','periods','musters','muster_shares','audit','outbox','idempotency'] LOOP EXECUTE format('ALTER TABLE eoms.%I ENABLE ROW LEVEL SECURITY',tab); EXECUTE format('ALTER TABLE eoms.%I FORCE ROW LEVEL SECURITY',tab); EXECUTE format('CREATE POLICY estate_scope ON eoms.%I TO eoms_app USING(eoms.is_member(estate_id)) WITH CHECK(eoms.is_member(estate_id))',tab); END LOOP; END $$;
GRANT SELECT ON eoms.users,eoms.companies,eoms.estates,eoms.memberships,eoms.workers,eoms.occurrences,eoms.periods TO eoms_app;
GRANT SELECT,INSERT,DELETE ON eoms.sessions TO eoms_app;
GRANT SELECT,INSERT,UPDATE ON eoms.musters TO eoms_app;
GRANT SELECT,INSERT ON eoms.muster_shares,eoms.audit,eoms.outbox,eoms.idempotency TO eoms_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA eoms TO eoms_app;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA eoms FROM PUBLIC;
GRANT EXECUTE ON FUNCTION eoms.actor_id(),eoms.is_member(uuid) TO eoms_app;
